/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiNewsRouteImport } from './routes/api/news'
import { Route as ApiChatTravelRouteImport } from './routes/api/chat-travel'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppViagensRouteImport } from './routes/_app.viagens'
import { Route as AppTarefasRouteImport } from './routes/_app.tarefas'
import { Route as AppReservasRouteImport } from './routes/_app.reservas'
import { Route as AppProjetosRouteImport } from './routes/_app.projetos'
import { Route as AppNotasRouteImport } from './routes/_app.notas'
import { Route as AppLinksRouteImport } from './routes/_app.links'
import { Route as AppFinancasRouteImport } from './routes/_app.financas'
import { Route as AppFicheirosRouteImport } from './routes/_app.ficheiros'
import { Route as AppDriveRouteImport } from './routes/_app.drive'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAiRouteImport } from './routes/_app.ai'
import { Route as AppViagensIndexRouteImport } from './routes/_app.viagens.index'
import { Route as AppReservasIndexRouteImport } from './routes/_app.reservas.index'
import { Route as AppDriveIndexRouteImport } from './routes/_app.drive.index'
import { Route as AppAiIndexRouteImport } from './routes/_app.ai.index'
import { Route as AppViagensTripIdRouteImport } from './routes/_app.viagens.$tripId'
import { Route as AppDriveStarredRouteImport } from './routes/_app.drive.starred'
import { Route as AppDriveRecentRouteImport } from './routes/_app.drive.recent'
import { Route as AppAiThreadIdRouteImport } from './routes/_app.ai.$threadId'
import { Route as AppDriveFolderFolderIdRouteImport } from './routes/_app.drive.folder.$folderId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatTravelRoute = ApiChatTravelRouteImport.update({
  id: '/api/chat-travel',
  path: '/api/chat-travel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppViagensRoute = AppViagensRouteImport.update({
  id: '/viagens',
  path: '/viagens',
  getParentRoute: () => AppRoute,
} as any)
const AppTarefasRoute = AppTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AppRoute,
} as any)
const AppReservasRoute = AppReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosRoute = AppProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AppRoute,
} as any)
const AppNotasRoute = AppNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => AppRoute,
} as any)
const AppLinksRoute = AppLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancasRoute = AppFinancasRouteImport.update({
  id: '/financas',
  path: '/financas',
  getParentRoute: () => AppRoute,
} as any)
const AppFicheirosRoute = AppFicheirosRouteImport.update({
  id: '/ficheiros',
  path: '/ficheiros',
  getParentRoute: () => AppRoute,
} as any)
const AppDriveRoute = AppDriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppViagensIndexRoute = AppViagensIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppViagensRoute,
} as any)
const AppReservasIndexRoute = AppReservasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReservasRoute,
} as any)
const AppDriveIndexRoute = AppDriveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDriveRoute,
} as any)
const AppAiIndexRoute = AppAiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAiRoute,
} as any)
const AppViagensTripIdRoute = AppViagensTripIdRouteImport.update({
  id: '/$tripId',
  path: '/$tripId',
  getParentRoute: () => AppViagensRoute,
} as any)
const AppDriveStarredRoute = AppDriveStarredRouteImport.update({
  id: '/starred',
  path: '/starred',
  getParentRoute: () => AppDriveRoute,
} as any)
const AppDriveRecentRoute = AppDriveRecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => AppDriveRoute,
} as any)
const AppAiThreadIdRoute = AppAiThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AppAiRoute,
} as any)
const AppDriveFolderFolderIdRoute = AppDriveFolderFolderIdRouteImport.update({
  id: '/folder/$folderId',
  path: '/folder/$folderId',
  getParentRoute: () => AppDriveRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai': typeof AppAiRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/drive': typeof AppDriveRouteWithChildren
  '/ficheiros': typeof AppFicheirosRoute
  '/financas': typeof AppFinancasRoute
  '/links': typeof AppLinksRoute
  '/notas': typeof AppNotasRoute
  '/projetos': typeof AppProjetosRoute
  '/reservas': typeof AppReservasRouteWithChildren
  '/tarefas': typeof AppTarefasRoute
  '/viagens': typeof AppViagensRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/chat-travel': typeof ApiChatTravelRoute
  '/api/news': typeof ApiNewsRoute
  '/ai/$threadId': typeof AppAiThreadIdRoute
  '/drive/recent': typeof AppDriveRecentRoute
  '/drive/starred': typeof AppDriveStarredRoute
  '/viagens/$tripId': typeof AppViagensTripIdRoute
  '/ai/': typeof AppAiIndexRoute
  '/drive/': typeof AppDriveIndexRoute
  '/reservas/': typeof AppReservasIndexRoute
  '/viagens/': typeof AppViagensIndexRoute
  '/drive/folder/$folderId': typeof AppDriveFolderFolderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/ficheiros': typeof AppFicheirosRoute
  '/financas': typeof AppFinancasRoute
  '/links': typeof AppLinksRoute
  '/notas': typeof AppNotasRoute
  '/projetos': typeof AppProjetosRoute
  '/tarefas': typeof AppTarefasRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-travel': typeof ApiChatTravelRoute
  '/api/news': typeof ApiNewsRoute
  '/ai/$threadId': typeof AppAiThreadIdRoute
  '/drive/recent': typeof AppDriveRecentRoute
  '/drive/starred': typeof AppDriveStarredRoute
  '/viagens/$tripId': typeof AppViagensTripIdRoute
  '/ai': typeof AppAiIndexRoute
  '/drive': typeof AppDriveIndexRoute
  '/reservas': typeof AppReservasIndexRoute
  '/viagens': typeof AppViagensIndexRoute
  '/drive/folder/$folderId': typeof AppDriveFolderFolderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/ai': typeof AppAiRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/drive': typeof AppDriveRouteWithChildren
  '/_app/ficheiros': typeof AppFicheirosRoute
  '/_app/financas': typeof AppFinancasRoute
  '/_app/links': typeof AppLinksRoute
  '/_app/notas': typeof AppNotasRoute
  '/_app/projetos': typeof AppProjetosRoute
  '/_app/reservas': typeof AppReservasRouteWithChildren
  '/_app/tarefas': typeof AppTarefasRoute
  '/_app/viagens': typeof AppViagensRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/chat-travel': typeof ApiChatTravelRoute
  '/api/news': typeof ApiNewsRoute
  '/_app/ai/$threadId': typeof AppAiThreadIdRoute
  '/_app/drive/recent': typeof AppDriveRecentRoute
  '/_app/drive/starred': typeof AppDriveStarredRoute
  '/_app/viagens/$tripId': typeof AppViagensTripIdRoute
  '/_app/ai/': typeof AppAiIndexRoute
  '/_app/drive/': typeof AppDriveIndexRoute
  '/_app/reservas/': typeof AppReservasIndexRoute
  '/_app/viagens/': typeof AppViagensIndexRoute
  '/_app/drive/folder/$folderId': typeof AppDriveFolderFolderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ai'
    | '/dashboard'
    | '/drive'
    | '/ficheiros'
    | '/financas'
    | '/links'
    | '/notas'
    | '/projetos'
    | '/reservas'
    | '/tarefas'
    | '/viagens'
    | '/api/chat'
    | '/api/chat-travel'
    | '/api/news'
    | '/ai/$threadId'
    | '/drive/recent'
    | '/drive/starred'
    | '/viagens/$tripId'
    | '/ai/'
    | '/drive/'
    | '/reservas/'
    | '/viagens/'
    | '/drive/folder/$folderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/ficheiros'
    | '/financas'
    | '/links'
    | '/notas'
    | '/projetos'
    | '/tarefas'
    | '/api/chat'
    | '/api/chat-travel'
    | '/api/news'
    | '/ai/$threadId'
    | '/drive/recent'
    | '/drive/starred'
    | '/viagens/$tripId'
    | '/ai'
    | '/drive'
    | '/reservas'
    | '/viagens'
    | '/drive/folder/$folderId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/ai'
    | '/_app/dashboard'
    | '/_app/drive'
    | '/_app/ficheiros'
    | '/_app/financas'
    | '/_app/links'
    | '/_app/notas'
    | '/_app/projetos'
    | '/_app/reservas'
    | '/_app/tarefas'
    | '/_app/viagens'
    | '/api/chat'
    | '/api/chat-travel'
    | '/api/news'
    | '/_app/ai/$threadId'
    | '/_app/drive/recent'
    | '/_app/drive/starred'
    | '/_app/viagens/$tripId'
    | '/_app/ai/'
    | '/_app/drive/'
    | '/_app/reservas/'
    | '/_app/viagens/'
    | '/_app/drive/folder/$folderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiChatTravelRoute: typeof ApiChatTravelRoute
  ApiNewsRoute: typeof ApiNewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-travel': {
      id: '/api/chat-travel'
      path: '/api/chat-travel'
      fullPath: '/api/chat-travel'
      preLoaderRoute: typeof ApiChatTravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/viagens': {
      id: '/_app/viagens'
      path: '/viagens'
      fullPath: '/viagens'
      preLoaderRoute: typeof AppViagensRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tarefas': {
      id: '/_app/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AppTarefasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservas': {
      id: '/_app/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof AppReservasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projetos': {
      id: '/_app/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AppProjetosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notas': {
      id: '/_app/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof AppNotasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/links': {
      id: '/_app/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof AppLinksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financas': {
      id: '/_app/financas'
      path: '/financas'
      fullPath: '/financas'
      preLoaderRoute: typeof AppFinancasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ficheiros': {
      id: '/_app/ficheiros'
      path: '/ficheiros'
      fullPath: '/ficheiros'
      preLoaderRoute: typeof AppFicheirosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/drive': {
      id: '/_app/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof AppDriveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/viagens/': {
      id: '/_app/viagens/'
      path: '/'
      fullPath: '/viagens/'
      preLoaderRoute: typeof AppViagensIndexRouteImport
      parentRoute: typeof AppViagensRoute
    }
    '/_app/reservas/': {
      id: '/_app/reservas/'
      path: '/'
      fullPath: '/reservas/'
      preLoaderRoute: typeof AppReservasIndexRouteImport
      parentRoute: typeof AppReservasRoute
    }
    '/_app/drive/': {
      id: '/_app/drive/'
      path: '/'
      fullPath: '/drive/'
      preLoaderRoute: typeof AppDriveIndexRouteImport
      parentRoute: typeof AppDriveRoute
    }
    '/_app/ai/': {
      id: '/_app/ai/'
      path: '/'
      fullPath: '/ai/'
      preLoaderRoute: typeof AppAiIndexRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/viagens/$tripId': {
      id: '/_app/viagens/$tripId'
      path: '/$tripId'
      fullPath: '/viagens/$tripId'
      preLoaderRoute: typeof AppViagensTripIdRouteImport
      parentRoute: typeof AppViagensRoute
    }
    '/_app/drive/starred': {
      id: '/_app/drive/starred'
      path: '/starred'
      fullPath: '/drive/starred'
      preLoaderRoute: typeof AppDriveStarredRouteImport
      parentRoute: typeof AppDriveRoute
    }
    '/_app/drive/recent': {
      id: '/_app/drive/recent'
      path: '/recent'
      fullPath: '/drive/recent'
      preLoaderRoute: typeof AppDriveRecentRouteImport
      parentRoute: typeof AppDriveRoute
    }
    '/_app/ai/$threadId': {
      id: '/_app/ai/$threadId'
      path: '/$threadId'
      fullPath: '/ai/$threadId'
      preLoaderRoute: typeof AppAiThreadIdRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/drive/folder/$folderId': {
      id: '/_app/drive/folder/$folderId'
      path: '/folder/$folderId'
      fullPath: '/drive/folder/$folderId'
      preLoaderRoute: typeof AppDriveFolderFolderIdRouteImport
      parentRoute: typeof AppDriveRoute
    }
  }
}

interface AppAiRouteChildren {
  AppAiThreadIdRoute: typeof AppAiThreadIdRoute
  AppAiIndexRoute: typeof AppAiIndexRoute
}

const AppAiRouteChildren: AppAiRouteChildren = {
  AppAiThreadIdRoute: AppAiThreadIdRoute,
  AppAiIndexRoute: AppAiIndexRoute,
}

const AppAiRouteWithChildren = AppAiRoute._addFileChildren(AppAiRouteChildren)

interface AppDriveRouteChildren {
  AppDriveRecentRoute: typeof AppDriveRecentRoute
  AppDriveStarredRoute: typeof AppDriveStarredRoute
  AppDriveIndexRoute: typeof AppDriveIndexRoute
  AppDriveFolderFolderIdRoute: typeof AppDriveFolderFolderIdRoute
}

const AppDriveRouteChildren: AppDriveRouteChildren = {
  AppDriveRecentRoute: AppDriveRecentRoute,
  AppDriveStarredRoute: AppDriveStarredRoute,
  AppDriveIndexRoute: AppDriveIndexRoute,
  AppDriveFolderFolderIdRoute: AppDriveFolderFolderIdRoute,
}

const AppDriveRouteWithChildren = AppDriveRoute._addFileChildren(
  AppDriveRouteChildren,
)

interface AppReservasRouteChildren {
  AppReservasIndexRoute: typeof AppReservasIndexRoute
}

const AppReservasRouteChildren: AppReservasRouteChildren = {
  AppReservasIndexRoute: AppReservasIndexRoute,
}

const AppReservasRouteWithChildren = AppReservasRoute._addFileChildren(
  AppReservasRouteChildren,
)

interface AppViagensRouteChildren {
  AppViagensTripIdRoute: typeof AppViagensTripIdRoute
  AppViagensIndexRoute: typeof AppViagensIndexRoute
}

const AppViagensRouteChildren: AppViagensRouteChildren = {
  AppViagensTripIdRoute: AppViagensTripIdRoute,
  AppViagensIndexRoute: AppViagensIndexRoute,
}

const AppViagensRouteWithChildren = AppViagensRoute._addFileChildren(
  AppViagensRouteChildren,
)

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppDriveRoute: typeof AppDriveRouteWithChildren
  AppFicheirosRoute: typeof AppFicheirosRoute
  AppFinancasRoute: typeof AppFinancasRoute
  AppLinksRoute: typeof AppLinksRoute
  AppNotasRoute: typeof AppNotasRoute
  AppProjetosRoute: typeof AppProjetosRoute
  AppReservasRoute: typeof AppReservasRouteWithChildren
  AppTarefasRoute: typeof AppTarefasRoute
  AppViagensRoute: typeof AppViagensRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDriveRoute: AppDriveRouteWithChildren,
  AppFicheirosRoute: AppFicheirosRoute,
  AppFinancasRoute: AppFinancasRoute,
  AppLinksRoute: AppLinksRoute,
  AppNotasRoute: AppNotasRoute,
  AppProjetosRoute: AppProjetosRoute,
  AppReservasRoute: AppReservasRouteWithChildren,
  AppTarefasRoute: AppTarefasRoute,
  AppViagensRoute: AppViagensRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiChatTravelRoute: ApiChatTravelRoute,
  ApiNewsRoute: ApiNewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
